### ISSUE TITLE
Support for 1.18.2!

### ISSUE THREAD

**Issue by JustSimplyKyle** [solonovamax/AntiIgnoringChunk#1]
Yes, this mod breaks in 1.18.2
https://mclo.gs/BcXI7GA
I could do a single mod test if you need it

**Comment by JustSimplyKyle** [comment]
Yeppp still breaks
https://mclo.gs/rHwF9Sb

**Comment by solonovamax** [comment]
My bad, gimme a sec to update it.

It won't be hard, it'll just take a few seconds.

**Comment by solonovamax** [comment]
Updated to 1.18.2

**Comment by JustSimplyKyle** [comment]
Wait you just changed log4j into slf4j
No wonder you said it's an few second fix lol

**Comment by solonovamax** [comment]
@KyleUltimate ya pretty much lol

At first I thought it was just a mappings update, which would have been even quicker, but swapping to slf4j is equally simple.

This mod is very lightweight & super easy to update since it does so little
